# Netzwerk-Identität
node-ip: "192.168.178.211"
advertise-address: "192.168.178.211"
node-external-ip: "192.168.178.211"
# HA / etcd Initialisierung
cluster-init: true
# Failover Timeout heruntersetzen
kube-controller-manager-arg:
  - "node-monitor-grace-period=20s"
kubelet-arg:
  - "node-status-update-frequency=5s"
# Deaktiviert den Standard-Loadbalancer (Klipper), damit kube-vip übernehmen kann
disable:
  - servicelb
  - traefik
# Hier können später weitere Parameter rein (z.B. tls-san für die VIP)
tls-san:
  - "192.168.178.220"
  - "k3s-ha.local"
# Hybrid-Cluster Optimierung (Raspberry Pi-Kompatibilität)
etcd-expose-metrics: true
write-kubeconfig-mode: "0644"