server: https://192.168.178.211:6443
token: "<K3S_JOIN_TOKEN>"
node-ip: "192.168.178.212" # Die IP dieses zweiten PCs
advertise-address: "192.168.178.212"
node-external-ip: "192.168.178.212"
disable:
  - servicelb
  - traefik
tls-san:
  - "192.168.178.220"
  - "k3s-ha.local"
etcd-expose-metrics: true
write-kubeconfig-mode: 644
