apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb3-pv-node2
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: influxdb3-storage
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.2
  nfs:
    path: /influxdb3
    server: smarthomeclusternode2