apiVersion: v1
kind: PersistentVolume
metadata:
  name: nodered-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: nodered-storage
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.2
  nfs:
    path: /mnt/ssd/nodered
    server: smarthomepi2