apiVersion: v2
name: smarthomedatahub
description: A Helm chart for SmartHomeDataHub - Sending data from MQTT to InfluxDB
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - mqtt
  - iot
maintainers:
  - name: tschissler
