---
- name: Install Longhorn node dependencies
  ansible.builtin.apt:
    name:
      - jq
      - open-iscsi
      - nfs-common
      - util-linux
    state: present
    update_cache: true

- name: Load iscsi_tcp module
  ansible.builtin.command: modprobe iscsi_tcp
  changed_when: false
  failed_when: false

- name: Ensure iscsi_tcp module loads on boot
  ansible.builtin.lineinfile:
    path: /etc/modules
    line: iscsi_tcp
    create: true

- name: Enable and start iscsid
  ansible.builtin.service:
    name: iscsid
    enabled: true
    state: started

- name: Ensure Longhorn data path exists
  ansible.builtin.file:
    path: "{{ longhorn_data_path }}"
    state: directory
    mode: '0755'
