apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto-pv-node2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: mosquitto-storage
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.2
  nfs:
    path: /mnt/ssd/mosquitto
    server: smarthomeclusternode2