apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv-node2
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: influxdb-storage
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.2
  nfs:
    path: /grafana
    server: smarthomeclusternode2