- import_playbook: plays/check-connectivity.yml
- import_playbook: plays/deploy-ssh-key.yml
- import_playbook: plays/prepare-ethernet.yml
- import_playbook: plays/install-nano.yml
- import_playbook: plays/network-config.yml
- import_playbook: plays/raspi-cgroups.yml
- import_playbook: plays/install-k3s.yml

# NOTE: Temporarily disabled. Run kube-vip explicitly once the cluster is stable.
# - import_playbook: plays/configure-kubevip.yml