apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smarthomeweb
  namespace: smarthome
  labels:
    app: smarthomeweb
spec:
  ingressClassName: traefik
  rules:
  - host: smarthome.intern
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: smarthomeweb
            port:
              number: 8080
